routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::localized(function () {
	Route::get('/', 'Frontend\HomeController@index')->name('index')->middleware('cacheable:2630000');;
	Route::get('/home', 'Frontend\HomeController@index')->name('home');
	Route::resource('blogs', 'Backend\BlogController');
	Route::get('/manage-blogs', 'Backend\BlogController@manageIndex')->name('manage-blogs');
	Auth::routes(['verify' => true]);
	Route::resource('contact-us', 'Backend\ContactUsController');
	Route::resource('divisions', 'Locations\DivisionController');
	Route::resource('districts', 'Locations\DistrictController');
	Route::resource('upazilas', 'Locations\UpazilaController');
	Route::resource('unions', 'Locations\UnionController');
	Route::resource('orders', 'Backend\OrderController');
	Route::get('cart', 'Backend\OrderController@cart')->name('cart');
	Route::get('checkout', 'Backend\OrderController@checkout')->name('checkout');
	Route::get('order-complete', 'Backend\OrderController@orderComplete')->name('order-complete');
	Route::get('card-payment/{id}', 'Frontend\StripePaymentController@stripe')->name('card-payment');
	Route::post('stripe', 'Frontend\StripePaymentController@stripePost')->name('stripe.post');

	Route::get('login/{social}', 'Backend\SocialLoginController@redirectToProvider')->name('social.callback');
	Route::get('login/{social}/callback', 'Backend\SocialLoginController@handleProviderCallback')->name('social.redirect');
	Route::get('privacy-policy', 'Frontend\HomeController@privacyPolicy')->name('privacy-policy');
	Route::get('terms-conditions', 'Frontend\HomeController@privacyPolicy')->name('terms-conditions');

	//Routes for dashboard
	Route::group(['middleware' => ['auth', 'verified']], function () {
		Route::resource('cashbooks', 'Backend\CashbookController');
		Route::resource('categories', 'Backend\CategoryController')->middleware('moderator:Category');
		Route::get('chats/delete/{id?}', 'Backend\ChatController@destroy')->name('chats.destroy');
		Route::get('chats/block/{id?}', 'Backend\ChatController@block')->name('chats.block');
		Route::resource('chats', 'Backend\ChatController')->except(['destroy']);
		Route::get('checkout-login', 'Backend\OrderController@checkoutLogin')->name('checkout-login');
		Route::resource('colors', 'Backend\ColorController')->middleware('moderator:Color');
		Route::get('/dashboard', 'Backend\DashboardController@dashboard')->name('dashboard');
		Route::resource('home-sliders', 'Backend\ColorController')->middleware('moderator:Color');
		Route::resource('notifications', 'Backend\NotificationController');
		Route::get('notifications-all', 'Backend\NotificationController@all')->name('notifications.all');
		Route::resource('order-details', 'Backend\OrderDetailController');
		Route::get('orders-incomplete', 'Backend\OrderController@incomplete')->name('orders.incomplete');
		Route::resource('order-statuses', 'Backend\OrderStatusController')->middleware('moderator:Order Status');
		Route::get('orders-user', 'Backend\OrderController@user')->name('orders.user');
		Route::resource('payments', 'Backend\PaymentController')->middleware('moderator:Payment');
		Route::resource('permissions', 'Backend\PermissionController')->middleware('moderator:Permission');
		Route::put('permissions-update', 'Backend\PermissionController@updateList')->name('permissions.update.list')->middleware('moderator:Permission');
		Route::get('manage-products', 'Backend\ProductController@manageIndex')->name('manage-products.index')->middleware('moderator:Product');
		Route::resource('manage-products', 'Backend\ProductController')->except(['index', 'show'])->middleware('moderator:Product');
		Route::resource('regions', 'Locations\RegionController')->middleware('moderator:Location');
		Route::resource('shippers', 'Backend\ShipperController')->middleware('moderator:Shipper');
		Route::resource('sizes', 'Backend\SizeController')->middleware('moderator:Size');
		Route::resource('suppliers', 'Backend\SupplierController')->middleware('moderator:Supplier');
		Route::resource('units', 'Backend\UnitController')->middleware('moderator:Unit');
		Route::resource('users', 'Backend\UserController');
	});
	Route::resource('products', 'Backend\ProductController')->only(['index', 'show']);
	Route::post('subscriptions', 'Backend\ContactUsController@subscribe')->name('subscriptions.store');
	Route::get('sitemap.xml', 'Backend\AccessoriesController@sitemap');
});
Route::get('clear-cache', 'Backend\AccessoriesController@clearCache');
Route::get('cache', 'Backend\AccessoriesController@cache');

app/Http/Controllers/Locations/DistrictController.php
<?php

namespace App\Http\Controllers\Locations;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Locations\District;

class DistrictController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		$districts = District::select('id', 'name')->get();
		return $districts;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $district = District::select('id', 'name')->where('id', $id)->with('upazilas', 'regions')->get();
		return $district;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Locations/DivisionController.php
<?php

namespace App\Http\Controllers\Locations;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use App\Locations\Division;

class DivisionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $division = Division::select('id', 'name')->get();
		return $division;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();
		return view('backend.locations.divisions.create', compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->except('_token', '_method');
		Division::find($id)->update($data);
		return redirect(route('divisions.index'))->with('message', 'Supplier created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $division = Division::select('id', 'name')->where('id', $id)->with('districts', 'regions')->get();
		return $division;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Auth::user();
        $division = Division::find($id);
		return view('backend.locations.divisions.create', compact('user', 'division'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->except('_token', '_method');
		$division = Division::find($id);
		$division->update($data);
		
		return redirect(route('divisions.index'))->with('message', 'Division updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $division = Division::find($id);
		$division->delete();
		return redirect()->back()->with('message', 'Division has been deleted');
    }
}

app/Http/Controllers/Locations/RegionController.php
<?php

namespace App\Http\Controllers\Locations;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use App\Locations\Division;
use App\Locations\District;
use App\Locations\Region;

class RegionController extends Controller
{
	public function __construct()
	{
		$this->middleware('moderatorOrOwner:User');
	}
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		$regions = Region::all();
		return view('backend.locations.regions.index', compact('regions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
		$divisions = Division::select('id', 'name')->orderBy('name')->get();
		$districts = District::select('id', 'name', 'division_id')->orderBy('name')->get();
		return view('backend.locations.regions.create', compact('divisions', 'districts'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->except('_token', '_method');
		Region::create($data);
		return redirect(route('regions.index'))->with('message', 'Region created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
		$region = Region::find($id);
		return view('backend.locations.regions.show', compact('region'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
		$divisions = Division::select('id', 'name')->orderBy('name')->get();
		$districts = District::select('id', 'name', 'division_id')->orderBy('name')->get();
        $region = Region::find($id);
		return view('backend.locations.regions.create', compact('region', 'divisions', 'districts'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->except('_token', '_method');
		$region = Region::find($id);
		$region->update($data);
		
		return redirect(route('regions.index'))->with('message', 'Region updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $region = Region::find($id);
		$region->delete();
		return redirect()->back()->with('message', 'Region has been deleted');
    }
}

app/Http/Controllers/Locations/UnionController.php
<?php

namespace App\Http\Controllers\Locations;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Locations\Union;

class UnionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $unions = Union::select('id', 'name')->get();
		return $unions;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $union = Union::select('id', 'name')->where('id', $id)->with('regions')->get();
		return $union;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Locations/UpazilaController.php
<?php

namespace App\Http\Controllers\Locations;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Locations\Upazila;

class UpazilaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $upazilas = Upazila::select('id', 'name')->get();
		return $upazilas;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $upazila = Upazila::select('id', 'name')->where('id', $id)->with('unions')->get();
		return $upazila;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/locations/regions/create.blade.php
@extends('layouts.dashboard')
@section('title')
{{ __(isset($region)?'Update region':'Create region') }}
@endsection
@section('content')
<div class="content-wrapper">
	<div class="container-fluid">
		<section class="content-header">
			<h3>Category <small>{{ isset($region)?'edit':'create' }}</small></h3>
			<ol class="breadcrumb">
				<li><a href="#"><i class="fa fa-dashboard"></i> Dashboard</a></li>
				<li><a href="#">Regions</a></li>
				<li class="active">{{ isset($region)?'Edit':'Create' }}</li>
			</ol>
		</section>
		@if(session()->has('message'))
		<div class="alert alert-warning">
			{{ session()->get('message') }}
		</div>
		@endif
		<div class="row">
			<div class="col-12">
				<div class="box box-info">
					<div class="box-header with-border">
						<h3 class="box-title"><i class="fa fa-edit"></i> {{ __(isset($region)?'Update region':'Create region') }}</h3>
						<div class="box-tools float-right">
							<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
							</button>
							<button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
						</div>
					</div>
					<div class="box-body">
						<div class="row pt-2">
							<div class="col-12"><!--left col-->
								<form action="@if(isset($region)) {{ route('regions.update', $region->id) }} @else {{ route('regions.store') }} @endif" method="post" enctype="multipart/form-data">
									@csrf
									@if(isset($region))
										@method('PUT')
									@endif
									<div class="form-group">
										<label for="division_id">Select Division</label>
										<select id="division" name="division_id" class="custom-select" id="division_id">
                    						<option value="0" selected>--Select city--</option>
                    						@foreach($divisions as $division)
                    						<option value="{{ $division->id }}">{{ $division->name ?? '' }}</option>
                    						@endforeach
                    					</select>
									</div>
									<div class="form-group">
										<label for="name">Name</label>
										<input id="name" type="text" class="form-control" name="name" value="{{ $region->name ?? '' }}" placeholder="First name" title="Enter your first name if any." />
									</div>
									<div class="form-group mt-3">
										<button class="btn btn-success btn-theme" type="submit">{{ __(isset($region)?'Update':'Save') }}</button>
									</div>
								</form>
							</div><!--/col-9-->
						</div><!--/row-->
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@section('style')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.css" rel="stylesheet">
@endsection
@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.js"></script>
    <script>
      $('.editor-tools').summernote({
        placeholder: 'Enter email body',
        tabsize: 2,
        height: 100
      });
    </script>
@endsection

resources/views/backend/locations/regions/index.blade.php
@extends('layouts.dashboard')
@section('title')
{{ __('All Regions') }}
@endsection
@section('content')
<div class="content-wrapper">
	<div class="container-fluid">
		<section class="content-header">
			<h3>Region <small>all</small></h3>
			<ol class="breadcrumb">
				<li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
				<li class="active">Regions</li>
			</ol>
		</section>
		@if(session()->has('message'))
		<div class="alert alert-warning">
			{{ session()->get('message') }}
		</div>
		@endif
		<div class="row">
			<div class="col-12">
				<div class="box box-info">
					<div class="box-header with-border">
						<h3 class="box-title"><i class="fa fa-credit-card mr-1"></i> {{ __('All Regions') }}</h3>
						<div class="box-tools float-right">
							<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
							</button>
							<button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
						</div>
					</div>
					<div class="box-body">
						<table id="dataTables" class="display nowrap" cellspacing="0" width="100%">
							<thead>
								<tr>
									<th>ID</th>
									<th>Name</th>
									<th>Edit</th>
									<th>Delete</th>
								</tr>
							</thead>
							<tbody>
								@foreach($regions as $region)
								<tr>
									<td>{{ $region->id }}</td>
									<td>{{ $region->name }}</td>
									<td><a href="{{ route('regions.edit', $region->id) }}" class="text-success fa fa-edit"></a></td>
									<td><a href="{{ route('regions.destroy', $region->id) }}" onclick="event.preventDefault(); document.getElementById('delete-form').action = this.href; document.getElementById('delete-form').submit.click();" class="text-danger fa fa-trash"></button></td>
								</tr>
								@endforeach
							</tbody>
							<tfoot>
								<tr>
									<th>ID</th>
									<th>Name</th>
									<th>Edit</th>
									<th>Delete</th>
								</tr>
							</tfoot>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@section('style')
	<!-- dataTables plugin -->
	<link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" media="all"/>
	<link href="https://cdn.datatables.net/responsive/2.1.0/css/responsive.dataTables.min.css" rel="stylesheet" media="screen">
	<link href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css" rel="stylesheet" media="all"/>
	<!-- /dataTables plugin -->
@endsection
@section('script')
	<!---dataTables plugin JavaScript -->
	<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/responsive/2.1.0/js/dataTables.responsive.min.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.flash.min.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
	<script src="{{ asset('js/dataTables.js') }}"></script>
	<!--/dataTables plugin JavaScript -->
@endsection