routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::localized(function () {
	Route::get('/', 'Frontend\HomeController@index')->name('index')->middleware('cacheable:2630000');;
	Route::get('/home', 'Frontend\HomeController@index')->name('home');
	Route::resource('blogs', 'Backend\BlogController');
	Route::get('/manage-blogs', 'Backend\BlogController@manageIndex')->name('manage-blogs');
	Auth::routes(['verify' => true]);
	Route::resource('contact-us', 'Backend\ContactUsController');
	Route::resource('divisions', 'Locations\DivisionController');
	Route::resource('districts', 'Locations\DistrictController');
	Route::resource('upazilas', 'Locations\UpazilaController');
	Route::resource('unions', 'Locations\UnionController');
	Route::resource('orders', 'Backend\OrderController');
	Route::get('cart', 'Backend\OrderController@cart')->name('cart');
	Route::get('checkout', 'Backend\OrderController@checkout')->name('checkout');
	Route::get('order-complete', 'Backend\OrderController@orderComplete')->name('order-complete');
	Route::get('card-payment/{id}', 'Frontend\StripePaymentController@stripe')->name('card-payment');
	Route::post('stripe', 'Frontend\StripePaymentController@stripePost')->name('stripe.post');

	Route::get('login/{social}', 'Backend\SocialLoginController@redirectToProvider')->name('social.callback');
	Route::get('login/{social}/callback', 'Backend\SocialLoginController@handleProviderCallback')->name('social.redirect');
	Route::get('privacy-policy', 'Frontend\HomeController@privacyPolicy')->name('privacy-policy');
	Route::get('terms-conditions', 'Frontend\HomeController@privacyPolicy')->name('terms-conditions');

	//Routes for dashboard
	Route::group(['middleware' => ['auth', 'verified']], function () {
		Route::resource('cashbooks', 'Backend\CashbookController');
		Route::resource('categories', 'Backend\CategoryController')->middleware('moderator:Category');
		Route::get('chats/delete/{id?}', 'Backend\ChatController@destroy')->name('chats.destroy');
		Route::get('chats/block/{id?}', 'Backend\ChatController@block')->name('chats.block');
		Route::resource('chats', 'Backend\ChatController')->except(['destroy']);
		Route::get('checkout-login', 'Backend\OrderController@checkoutLogin')->name('checkout-login');
		Route::resource('colors', 'Backend\ColorController')->middleware('moderator:Color');
		Route::get('/dashboard', 'Backend\DashboardController@dashboard')->name('dashboard');
		Route::resource('home-sliders', 'Backend\ColorController')->middleware('moderator:Color');
		Route::resource('notifications', 'Backend\NotificationController');
		Route::get('notifications-all', 'Backend\NotificationController@all')->name('notifications.all');
		Route::resource('order-details', 'Backend\OrderDetailController');
		Route::get('orders-incomplete', 'Backend\OrderController@incomplete')->name('orders.incomplete');
		Route::resource('order-statuses', 'Backend\OrderStatusController')->middleware('moderator:Order Status');
		Route::get('orders-user', 'Backend\OrderController@user')->name('orders.user');
		Route::resource('payments', 'Backend\PaymentController')->middleware('moderator:Payment');
		Route::resource('permissions', 'Backend\PermissionController')->middleware('moderator:Permission');
		Route::put('permissions-update', 'Backend\PermissionController@updateList')->name('permissions.update.list')->middleware('moderator:Permission');
		Route::get('manage-products', 'Backend\ProductController@manageIndex')->name('manage-products.index')->middleware('moderator:Product');
		Route::resource('manage-products', 'Backend\ProductController')->except(['index', 'show'])->middleware('moderator:Product');
		Route::resource('regions', 'Locations\RegionController')->middleware('moderator:Location');
		Route::resource('shippers', 'Backend\ShipperController')->middleware('moderator:Shipper');
		Route::resource('sizes', 'Backend\SizeController')->middleware('moderator:Size');
		Route::resource('suppliers', 'Backend\SupplierController')->middleware('moderator:Supplier');
		Route::resource('units', 'Backend\UnitController')->middleware('moderator:Unit');
		Route::resource('users', 'Backend\UserController');
	});
	Route::resource('products', 'Backend\ProductController')->only(['index', 'show']);
	Route::post('subscriptions', 'Backend\ContactUsController@subscribe')->name('subscriptions.store');
	Route::get('sitemap.xml', 'Backend\AccessoriesController@sitemap');
});
Route::get('clear-cache', 'Backend\AccessoriesController@clearCache');
Route::get('cache', 'Backend\AccessoriesController@cache');

app/Http/Controllers/Backend/AccessoriesController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use patie\Sitemap\SitemapGenerator;
use Artisan;

class AccessoriesController extends Controller
{
    public function sitemap() {
    	SitemapGenerator::create(url('/'))->writeToFile('sitemap.xml');
    }
    public function cache() {
    	Artisan::call('config:cache');
		Artisan::call('route:cache');
		return redirect()->route('index');
    }
    public function clearCache() {
    	Artisan::call('cache:clear');
		Artisan::call('view:clear');
		Artisan::call('config:clear');
		Artisan::call('route:clear');
		return redirect()->route('index');
    }
}

app/Http/Controllers/Backend/BlogController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use App\Blog;
use App\Category;
use Illuminate\Support\Facades\File;

class BlogController extends Controller {

    public function __construct() {
        $this->middleware('moderator:Product', ['except' => [
                'index', 'show'
        ]]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {
        
        $posts = Blog::orderBy('id', 'desc');
        if($request->category)
            $posts->where('category_id', $request->category);
        $posts = $posts->paginate(10);
        $categories = Category::all();
        return view('backend.blogs.index', compact('posts', 'categories'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function manageIndex() {
        $posts = Blog::orderBy('id', 'desc')->get();
        return view('backend.blogs.manage-index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $categories = Category::all();
        return view('backend.blogs.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $data = $request->except('_token', '_method');
        $data['user_id'] = Auth::user()->id;
        $file = $request->file('photo');
        if ($file) {
            $destination_path = 'assets/blogs';
            $new_name = time() . '.' . $file->getClientOriginalExtension();
            $file->move($destination_path, $new_name);
            $data['photo'] = $new_name;
        }
        $thumbnail = $request->file('thumbnail');
        if ($thumbnail) {
            $destination_path = 'assets/blogs';
            $new_name = time() . '-thumb.' . $file->getClientOriginalExtension();
            $file->move($destination_path, $new_name);
            $data['thumbnail'] = $new_name;
        }
        Blog::create($data);
        return redirect(route('manage-index'))->with('message', 'Blog created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {

        $post = Blog::find($id);
        $categories = Category::all();
        return view('backend.blogs.show', compact('post', 'categories'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $post = Blog::find($id);
        $categories = Category::all();
        return view('backend.blogs.create', compact('post', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        $data = $request->except('_token', '_method');
        $data['user_id'] = Auth::user()->id;
        $post = Blog::find($id);
        $file = $request->file('photo');
        $directory = '/assets/blogs/';
        if ($file) {
            $destination_path = 'assets/blogs';
            $new_name = time() . '.' . $file->getClientOriginalExtension();
            $file->move($destination_path, $new_name);
            $data['photo'] = $new_name;
            File::delete($directory . $post->photo);
        }
        $thumbnail = $request->file('thumbnail');
        if ($thumbnail) {
            $destination_path = 'assets/blogs';
            $new_name = time() . '-thumb.' . $file->getClientOriginalExtension();
            $file->move($destination_path, $new_name);
            $data['thumbnail'] = $new_name;
            File::delete($directory . $post->thumbnail);
        }
        $post->update($data);
        return redirect(route('blogs.index'))->with('message', 'Blog updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        $post = Blog::find($id);
        $directory = '/assets/blogs/';
        File::delete($directory . $post->photo);
        File::delete($directory . $post->thumbnail);
        $post->delete();
        return redirect()->back()->with('message', 'Blog has been deleted');
    }

}

app/Http/Controllers/Backend/CashbookController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Cashbook;
use Auth;

class CashbookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		$cashbooks = Cashbook::with('order', 'user')->latest()->paginate(50);
		
        return view('backend.cashbook.index', compact('cashbooks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.cashbook.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->except('_token', '_method');
		$data['owned_by'] = User::where('email', $request->receiver_email)->pluck('id');
		
		$cumulative_amount = Cashbook::latest()->pluck('cumulative_amount')->first();
		if($request->action == 'credit')
			$data['cumulative_amount'] = $cumulative_amount+$data['amount'];
		elseif($request->action == 'debit')
			$data['cumulative_amount'] = $cumulative_amount-$data['amount'];
		else
			return redirect()->back()->with('message', 'Error');
		$data['user_id'] = Auth::user()->id;
		Cashbook::create($data);
		return redirect(route('cashbooks.index'))->with('message', 'Transaction created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use App\Category;
use Illuminate\Support\Facades\File;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		
		$categories = Category::orderBy('id', 'desc')->get();
		return view('backend.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
		return view('backend.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
		$file = $request->file('picture');
		$data = $request->except('_token', '_method', 'files', 'picture');
		$category = Category::create($data);
		if($file) {
			$destination_path = 'assets/categories';
			$new_name = $category->id.'.'.$file->getClientOriginalExtension();
			$file->move($destination_path, $new_name);
			$data['picture'] = $new_name;
			$category->update($data);
		}
		return redirect(route('categories.index'))->with('message', 'Category created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
		
        $category = Category::find($id);
		return view('backend.categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
		
        $category = Category::find($id);
		return view('backend.categories.create', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
		$file = $request->file('picture');
		$data = $request->except('_token', '_method', 'files', 'picture');
		$category = Category::find($id);
		if($file) {
			$destination_path = 'assets/categories/';
			$new_name = $id.'.'.$file->getClientOriginalExtension();
			$file->move($destination_path, $new_name);
			$data['picture'] = $new_name;
		}
		$category->update($data);
		return redirect(route('categories.index'))->with('message', 'Category updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
		$category = Category::find($id);
		$directory = '/assets/categories/';
		File::delete($directory.$category->picture);
		$category->delete();
		return redirect()->back()->with('message', 'Category has been deleted');
    }
}

app/Http/Controllers/Backend/CommentController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use App\Comment;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		//
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
		$data = $request->except('_token', '_method');
		$data['user_id'] = Auth::user()->id;
		Comment::create($data);
		return redirect()->back()->with('message', 'Thank you for your comment');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
		//
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
		//
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
		//
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
		$comment = Comment::find($id);
		$comment->delete();
		return redirect()->back()->with('message', 'Comment has been deleted');
    }
}

resources/views/layouts/backend/bottom-bar.blade.php
@computer
<footer class="main-footer text-center">
	<div class="float-right">
		{{ __('Developed by') }} <b>rejauldu</b>
	</div>
	<strong>{{ __('Copyright') }} © {{ __(date('Y')) }} <a href="#">{{ config('app.name', 'Laravel') }}</a>.</strong> {{ __('All rights reserved') }}
</footer>
@endcomputer

resources/views/layouts/backend/footer.blade.php
		@auth
		<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
			@csrf
		</form>
		<form id="delete-form" action="#" method="POST" style="display: none;" onsubmit="return confirm('Are you sure you want to delete?');">
			@csrf
			{{ method_field('DELETE') }}
			<input type="submit" name="submit" />
		</form>
		@endauth
		<!-- Default Success Modal called from JavaScript -->
		<div class="modal fade" id="success-modal">
			<div class="modal-dialog modal-dialog-centered modal-sm">
				<div class="modal-content">
					<!-- Modal Header -->
					<div class="modal-header">
						<h4 class="modal-title">Success</h4>
						<button type="button" class="close" data-dismiss="modal">&times;</button>
					</div>
					<!-- Modal body -->
					<div class="modal-body text-success">
					Updated successfully
					</div>
					<!-- Modal footer -->
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Ok</button>
					</div>
				</div>
			</div>
		</div>
		<!-- Default Success Modal called from JavaScript -->
		<div class="modal fade" id="error-modal">
			<div class="modal-dialog modal-dialog-centered modal-sm">
				<div class="modal-content">
					<!-- Modal Header -->
					<div class="modal-header">
						<h4 class="modal-title">Error</h4>
						<button type="button" class="close" data-dismiss="modal">&times;</button>
					</div>
					<!-- Modal body -->
					<div class="modal-body text-danger">
					Error! Update error. Please try again.
					</div>
					<!-- Modal footer -->
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Ok</button>
					</div>
				</div>
			</div>
		</div>
	</div><!--end of #app-->
	<!-- Scripts -->
	<script src="{{ asset('js/app.js') }}?{{ time() }}"></script>
	<!-- Smooth Scroll -->
	<!--- Box JavaScript -->
	<script src="{{ asset('js/adminlte.min.js') }}"></script>
	<script src="{{ asset('js/demo.js') }}"></script>
	<script src="{{ asset('js/smooth-scroll.js') }}"></script>
	<!--- Box JavaScript -->
	<script src="{{ asset('js/theme.js') }}"></script>
	@yield('script')
</body>
</html>

resources/views/layouts/backend/header.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- CSRF Token -->
	<meta name="csrf-token" content="{{ csrf_token() }}">
	<!--base url for Script files -->
	<meta name="base-url" content="{{ url('/') }}">
	<title>@yield('title')</title>
	<link rel="icon" href="{{ asset('/assets/favicon.ico') }}" type="image/gif" sizes="16x16">
	<!-- Fonts -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
	<!-- All packages style -->
	<link rel="stylesheet" href="{{ asset('/css/app.css') }}">
	<!-- Box style -->
	<link rel="stylesheet" href="{{ asset('/css/adminlte.min.css') }}">
	<!-- AdminLTE Skins. Choose a skin from the css/skins
		folder instead of downloading all of them to reduce the load. -->
	<link rel="stylesheet" href="{{asset('css/skins/_all-skins.min.css')}}">
	<!-- Theme style -->
	<link rel="stylesheet" href="{{ asset('/css/theme.css') }}">
	@yield('style')
</head>
<body class="hold-transition skin-blue sidebar-mini">
	<div id="app" class="wrapper"><!-- #app for vuejs -->

resources/views/layouts/backend/top-bar.blade.php
<header class="main-header">
	<!-- Logo -->
	<a href="{{ url('/') }}" class="logo">
		<!-- mini logo for sidebar mini 50x50 pixels -->
		<span class="logo-mini"><b>O</b>B</span>
		<!-- logo for regular state and mobile devices -->
		<span class="logo-lg">{{ config('app.name') }}</span>
	</a>
	<!-- Header Navbar: style can be found in header.less -->
	<nav class="navbar navbar-expand-sm navbar-static-top theme-nav">
		<!-- Sidebar toggle button-->
		<a href="#" class="nav-link py-0 sidebar-toggle py-0" data-toggle="push-menu" role="button">
			<span class="sr-only">Toggle navigation</span>
		</a>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav ml-auto">
				<!-- Messages: style can be found in dropdown.less-->
				<li class="nav-item messages-menu" id="app">
					<a href="{{ route('chats.index') }}" class="nav-link py-0">
						<i class="fa fa-envelope-o"></i>
						@auth
						<chat-counter :user='@json($user)' :partner='@if(isset($partner)) @json($partner) @else "{}" @endif' :total_unread_message="@json($total_unread_message)"></chat-counter>
						@endauth
					</a>
				</li>
				<!-- Notifications: style can be found in dropdown.less -->
				@moderator(Notification)
				<li class="nav-item notifications-menu">
					<a href="{{ route('notifications.index') }}" class="nav-link py-0">
						<i class="fa fa-bell-o"></i>
						@php($unread = $user->unreadNotifications()->groupBy('notifiable_type')->count())
						@if($unread>0)
						<span class="badge badge-warning">{{ $unread }}</span>
						@endif
					</a>
				</li>
				@endmoderator
				@user
				<li class="nav-item notifications-menu">
					<a href="{{ route('notifications.index') }}" class="nav-link py-0">
						<i class="fa fa-bell-o"></i>
						@php($unread = $user->unreadNotifications()->groupBy('notifiable_type')->count())
						@if($unread>0)
						<span class="badge badge-warning">{{ $unread }}</span>
						@endif
					</a>
				</li>
				@enduser
				<!-- Tasks: style can be found in dropdown.less -->
				<li class="nav-item tasks-menu">
					<a href="{{ route('orders.incomplete') }}" class="nav-link py-0">
						<i class="fa fa-shopping-cart"></i>
						@if($incomplete_for_admin>0)
						<span class="badge badge-danger">{{ $incomplete_for_admin }}</span>
						@endif
					</a>
				</li>
				<!-- User Account: style can be found in dropdown.less -->
				<li class="nav-item dropdown user user-menu">
					<a href="#" class="nav-link py-0 dropdown-toggle" data-toggle="dropdown">
						<img src="/assets/profile/{{ $user->photo }}" class="user-image" alt="User Image">
						<span class="hidden-xs">{{ $user->name ?? '' }}</span>
					</a>
					<ul class="dropdown-menu dropdown-menu-right">
						<!-- User image -->
						<li class="user-header">
							<img src="/assets/profile/{{ $user->photo }}" class="img-circle" alt="User Image">
							<p>{{ $user->name ?? '' }} <small>{{ __('Since') }} {{ $user->created_at->date ?? '' }}</small></p>
						</li>
						<!-- Menu Body -->
						<!-- Menu Footer-->
						<li class="user-footer">
							<div class="pull-left">
								<a href="{{ route('users.edit', $user->id ?? '') }}" class="btn btn-default btn-flat">{{ __('Profile') }}</a>
							</div>
							<div class="pull-right">
								<a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" class="btn btn-default btn-flat">{{ __('Logout') }}</a>
							</div>
						</li>
					</ul>
				</li>
			</ul>
		</div>
	</nav>
</header>