routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::localized(function () {
	Route::get('/', 'Frontend\HomeController@index')->name('index')->middleware('cacheable:2630000');;
	Route::get('/home', 'Frontend\HomeController@index')->name('home');
	Route::resource('blogs', 'Backend\BlogController');
	Route::get('/manage-blogs', 'Backend\BlogController@manageIndex')->name('manage-blogs');
	Auth::routes(['verify' => true]);
	Route::resource('contact-us', 'Backend\ContactUsController');
	Route::resource('divisions', 'Locations\DivisionController');
	Route::resource('districts', 'Locations\DistrictController');
	Route::resource('upazilas', 'Locations\UpazilaController');
	Route::resource('unions', 'Locations\UnionController');
	Route::resource('orders', 'Backend\OrderController');
	Route::get('cart', 'Backend\OrderController@cart')->name('cart');
	Route::get('checkout', 'Backend\OrderController@checkout')->name('checkout');
	Route::get('order-complete', 'Backend\OrderController@orderComplete')->name('order-complete');
	Route::get('card-payment/{id}', 'Frontend\StripePaymentController@stripe')->name('card-payment');
	Route::post('stripe', 'Frontend\StripePaymentController@stripePost')->name('stripe.post');

	Route::get('login/{social}', 'Backend\SocialLoginController@redirectToProvider')->name('social.callback');
	Route::get('login/{social}/callback', 'Backend\SocialLoginController@handleProviderCallback')->name('social.redirect');
	Route::get('privacy-policy', 'Frontend\HomeController@privacyPolicy')->name('privacy-policy');
	Route::get('terms-conditions', 'Frontend\HomeController@privacyPolicy')->name('terms-conditions');

	//Routes for dashboard
	Route::group(['middleware' => ['auth', 'verified']], function () {
		Route::resource('cashbooks', 'Backend\CashbookController');
		Route::resource('categories', 'Backend\CategoryController')->middleware('moderator:Category');
		Route::get('chats/delete/{id?}', 'Backend\ChatController@destroy')->name('chats.destroy');
		Route::get('chats/block/{id?}', 'Backend\ChatController@block')->name('chats.block');
		Route::resource('chats', 'Backend\ChatController')->except(['destroy']);
		Route::get('checkout-login', 'Backend\OrderController@checkoutLogin')->name('checkout-login');
		Route::resource('colors', 'Backend\ColorController')->middleware('moderator:Color');
		Route::get('/dashboard', 'Backend\DashboardController@dashboard')->name('dashboard');
		Route::resource('home-sliders', 'Backend\ColorController')->middleware('moderator:Color');
		Route::resource('notifications', 'Backend\NotificationController');
		Route::get('notifications-all', 'Backend\NotificationController@all')->name('notifications.all');
		Route::resource('order-details', 'Backend\OrderDetailController');
		Route::get('orders-incomplete', 'Backend\OrderController@incomplete')->name('orders.incomplete');
		Route::resource('order-statuses', 'Backend\OrderStatusController')->middleware('moderator:Order Status');
		Route::get('orders-user', 'Backend\OrderController@user')->name('orders.user');
		Route::resource('payments', 'Backend\PaymentController')->middleware('moderator:Payment');
		Route::resource('permissions', 'Backend\PermissionController')->middleware('moderator:Permission');
		Route::put('permissions-update', 'Backend\PermissionController@updateList')->name('permissions.update.list')->middleware('moderator:Permission');
		Route::get('manage-products', 'Backend\ProductController@manageIndex')->name('manage-products.index')->middleware('moderator:Product');
		Route::resource('manage-products', 'Backend\ProductController')->except(['index', 'show'])->middleware('moderator:Product');
		Route::resource('regions', 'Locations\RegionController')->middleware('moderator:Location');
		Route::resource('shippers', 'Backend\ShipperController')->middleware('moderator:Shipper');
		Route::resource('sizes', 'Backend\SizeController')->middleware('moderator:Size');
		Route::resource('suppliers', 'Backend\SupplierController')->middleware('moderator:Supplier');
		Route::resource('units', 'Backend\UnitController')->middleware('moderator:Unit');
		Route::resource('users', 'Backend\UserController');
	});
	Route::resource('products', 'Backend\ProductController')->only(['index', 'show']);
	Route::post('subscriptions', 'Backend\ContactUsController@subscribe')->name('subscriptions.store');
	Route::get('sitemap.xml', 'Backend\AccessoriesController@sitemap');
});
Route::get('clear-cache', 'Backend\AccessoriesController@clearCache');
Route::get('cache', 'Backend\AccessoriesController@cache');

app/Http/Controllers/Backend/AccessoriesController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use patie\Sitemap\SitemapGenerator;
use Artisan;

class AccessoriesController extends Controller
{
    public function sitemap() {
    	SitemapGenerator::create(url('/'))->writeToFile('sitemap.xml');
    }
    public function cache() {
    	Artisan::call('config:cache');
		Artisan::call('route:cache');
		return redirect()->route('index');
    }
    public function clearCache() {
    	Artisan::call('cache:clear');
		Artisan::call('view:clear');
		Artisan::call('config:clear');
		Artisan::call('route:clear');
		return redirect()->route('index');
    }
}

app/Http/Controllers/Backend/BlogController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use App\Blog;
use App\Category;
use Illuminate\Support\Facades\File;

class BlogController extends Controller {

    public function __construct() {
        $this->middleware('moderator:Product', ['except' => [
                'index', 'show'
        ]]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {
        
        $posts = Blog::orderBy('id', 'desc');
        if($request->category)
            $posts->where('category_id', $request->category);
        $posts = $posts->paginate(10);
        $categories = Category::all();
        return view('backend.blogs.index', compact('posts', 'categories'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function manageIndex() {
        $posts = Blog::orderBy('id', 'desc')->get();
        return view('backend.blogs.manage-index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $categories = Category::all();
        return view('backend.blogs.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $data = $request->except('_token', '_method');
        $data['user_id'] = Auth::user()->id;
        $file = $request->file('photo');
        if ($file) {
            $destination_path = 'assets/blogs';
            $new_name = time() . '.' . $file->getClientOriginalExtension();
            $file->move($destination_path, $new_name);
            $data['photo'] = $new_name;
        }
        $thumbnail = $request->file('thumbnail');
        if ($thumbnail) {
            $destination_path = 'assets/blogs';
            $new_name = time() . '-thumb.' . $file->getClientOriginalExtension();
            $file->move($destination_path, $new_name);
            $data['thumbnail'] = $new_name;
        }
        Blog::create($data);
        return redirect(route('manage-index'))->with('message', 'Blog created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {

        $post = Blog::find($id);
        $categories = Category::all();
        return view('backend.blogs.show', compact('post', 'categories'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $post = Blog::find($id);
        $categories = Category::all();
        return view('backend.blogs.create', compact('post', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        $data = $request->except('_token', '_method');
        $data['user_id'] = Auth::user()->id;
        $post = Blog::find($id);
        $file = $request->file('photo');
        $directory = '/assets/blogs/';
        if ($file) {
            $destination_path = 'assets/blogs';
            $new_name = time() . '.' . $file->getClientOriginalExtension();
            $file->move($destination_path, $new_name);
            $data['photo'] = $new_name;
            File::delete($directory . $post->photo);
        }
        $thumbnail = $request->file('thumbnail');
        if ($thumbnail) {
            $destination_path = 'assets/blogs';
            $new_name = time() . '-thumb.' . $file->getClientOriginalExtension();
            $file->move($destination_path, $new_name);
            $data['thumbnail'] = $new_name;
            File::delete($directory . $post->thumbnail);
        }
        $post->update($data);
        return redirect(route('blogs.index'))->with('message', 'Blog updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        $post = Blog::find($id);
        $directory = '/assets/blogs/';
        File::delete($directory . $post->photo);
        File::delete($directory . $post->thumbnail);
        $post->delete();
        return redirect()->back()->with('message', 'Blog has been deleted');
    }

}

app/Http/Controllers/Backend/CashbookController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Cashbook;
use Auth;

class CashbookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		$cashbooks = Cashbook::with('order', 'user')->latest()->paginate(50);
		
        return view('backend.cashbook.index', compact('cashbooks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.cashbook.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->except('_token', '_method');
		$data['owned_by'] = User::where('email', $request->receiver_email)->pluck('id');
		
		$cumulative_amount = Cashbook::latest()->pluck('cumulative_amount')->first();
		if($request->action == 'credit')
			$data['cumulative_amount'] = $cumulative_amount+$data['amount'];
		elseif($request->action == 'debit')
			$data['cumulative_amount'] = $cumulative_amount-$data['amount'];
		else
			return redirect()->back()->with('message', 'Error');
		$data['user_id'] = Auth::user()->id;
		Cashbook::create($data);
		return redirect(route('cashbooks.index'))->with('message', 'Transaction created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use App\Category;
use Illuminate\Support\Facades\File;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		
		$categories = Category::orderBy('id', 'desc')->get();
		return view('backend.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
		return view('backend.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
		$file = $request->file('picture');
		$data = $request->except('_token', '_method', 'files', 'picture');
		$category = Category::create($data);
		if($file) {
			$destination_path = 'assets/categories';
			$new_name = $category->id.'.'.$file->getClientOriginalExtension();
			$file->move($destination_path, $new_name);
			$data['picture'] = $new_name;
			$category->update($data);
		}
		return redirect(route('categories.index'))->with('message', 'Category created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
		
        $category = Category::find($id);
		return view('backend.categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
		
        $category = Category::find($id);
		return view('backend.categories.create', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
		$file = $request->file('picture');
		$data = $request->except('_token', '_method', 'files', 'picture');
		$category = Category::find($id);
		if($file) {
			$destination_path = 'assets/categories/';
			$new_name = $id.'.'.$file->getClientOriginalExtension();
			$file->move($destination_path, $new_name);
			$data['picture'] = $new_name;
		}
		$category->update($data);
		return redirect(route('categories.index'))->with('message', 'Category updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
		$category = Category::find($id);
		$directory = '/assets/categories/';
		File::delete($directory.$category->picture);
		$category->delete();
		return redirect()->back()->with('message', 'Category has been deleted');
    }
}

app/Http/Controllers/Backend/CommentController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use App\Comment;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		//
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
		$data = $request->except('_token', '_method');
		$data['user_id'] = Auth::user()->id;
		Comment::create($data);
		return redirect()->back()->with('message', 'Thank you for your comment');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
		//
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
		//
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
		//
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
		$comment = Comment::find($id);
		$comment->delete();
		return redirect()->back()->with('message', 'Comment has been deleted');
    }
}

resources/views/backend/requested-more-infos/all.blade.php
@extends('layouts.dashboard')
@section('title')
{{ __('All Notifications') }}
@endsection
@section('content')
<div class="content-wrapper">
	<div class="container-fluid">
		<section class="content-header">
			<h3>Notification <small>all</small></h3>
			<ol class="breadcrumb">
				<li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
				<li class="active">Notifications</li>
			</ol>
		</section>
		@if(session()->has('message'))
		<div class="alert alert-warning">
			{{ session()->get('message') }}
		</div>
		@endif
		<div class="row">
			<div class="col-12">
				<div class="box box-info">
					<div class="box-header with-border">
						<h3 class="box-title"><i class="fa fa-bell mr-1"></i> {{ __('All Notifications') }}</h3>
						<div class="box-tools float-right">
							<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
							</button>
							<button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
						</div>
					</div>
					<div class="box-body">
						<table id="dataTables" class="display nowrap" cellspacing="0" width="100%">
							<thead>
								<tr>
									<th>ID</th>
									<th>Email</th>
									<th>Subject</th>
									<th>Created</th>
									<th>Read</th>
								</tr>
							</thead>
							<tbody>
								@foreach($notifications as $notification)
								<tr>
									<td>{{ $notification->id }}</td>
									<td>{{ $notification->user->email }}</td>
									<td>{{ json_decode($notification->data)->subject }}</td>
									<td>{{ $notification->created_at->format('jS M Y') }}</td>
									<td><a href="{{ route('notifications.show', $notification->id) }}" class="text-primary fa fa-eye"></a></td>
								</tr>
								@endforeach
							</tbody>
							<tfoot>
								<tr>
									<th>ID</th>
									<th>Email</th>
									<th>Subject</th>
									<th>Created</th>
									<th>Read</th>
								</tr>
							</tfoot>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@section('style')
	<!-- dataTables plugin -->
	<link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" media="all"/>
	<link href="https://cdn.datatables.net/responsive/2.1.0/css/responsive.dataTables.min.css" rel="stylesheet" media="screen">
	<link href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css" rel="stylesheet" media="all"/>
	<!-- /dataTables plugin -->
@endsection
@section('script')
	<!---dataTables plugin JavaScript -->
	<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/responsive/2.1.0/js/dataTables.responsive.min.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.flash.min.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
	<script src="{{ asset('js/dataTables.js') }}"></script>
	<!--/dataTables plugin JavaScript -->
@endsection

resources/views/backend/requested-more-infos/create.blade.php
@extends('layouts.dashboard')
@section('title')
Send Notification
@endsection
@section('content')
<div class="content-wrapper">
	<div class="container-fluid">
		<section class="content-header">
			<h3>Notification <small>Send</small></h3>
			<ol class="breadcrumb">
				<li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
				<li class="active">Send Email</li>
			</ol>
		</section>
		@if(session()->has('message'))
		<div class="alert alert-warning">
			{{ session()->get('message') }}
		</div>
		@endif
		<div class="row">
			<div class="col-12">
				<div class="box box-info">
					<div class="box-header with-border">
						<h3 class="box-title"><i class="fa fa-envelope mr-1"></i> {{ __('Send Notification') }}</h3>
						<div class="box-tools float-right">
							<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
							</button>
							<button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
						</div>
					</div>
					<div class="box-body">
						<div class="row pt-2">
							<div class="col-12 col-md-12">
								<ul class="nav nav-tabs">
									<li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#mail">To Email</a></li>
									<li class="nav-item"><a class="nav-link" data-toggle="tab" href="#database">In {{ config('app.name') ?? url('/') }}</a></li>
								</ul>
								<div class="tab-content mt-3">
									<div id="mail" class="tab-pane active">
										<form class="needs-validation" action="{{ route('notifications.store') }}" method="post">
											@csrf
											<div class="form-group">
												<div class="custom-control custom-radio custom-control-inline">
													<input type="radio" class="custom-control-input" id="individual1" name="user_amount" value="individual" checked>
													<label class="custom-control-label" for="individual1">Individual</label>
												</div>
												<div class="custom-control custom-radio custom-control-inline">
													<input type="radio" class="custom-control-input" id="all-user1" name="user_amount" value="all-user">
													<label class="custom-control-label" for="all-user1">All user</label>
												</div>
											</div>
											<div class="form-group">
												<label for="email1">Email:</label>
												<input type="email" name="email" class="form-control" value="{{ $email ?? '' }}" placeholder="Enter email ID" id="email1" required>
												<div class="valid-feedback">Valid.</div>
												<div class="invalid-feedback">Please fill out this field.</div>
											</div>
											<div class="form-group">
												<label for="subject1">Subject:</label>
												<input type="text" name="subject" class="form-control" placeholder="Subject of email" id="subject1" required>
												<div class="valid-feedback">Valid.</div>
												<div class="invalid-feedback">Please fill out this field.</div>
											</div>
											<!-- toolbar with suitable buttons and dialogues -->
											<div class="form-group">
												<label for="message1">Message:</label>
												<textarea name="body" class="form-control editor-tools" rows="5" id="message1" required></textarea>
												<div class="valid-feedback">Valid.</div>
												<div class="invalid-feedback">Please fill out this field.</div>
											</div>
											<button type="submit" name="mail" class="btn btn-theme" value="mail">Send</button>
										</form>
									</div>
									<div id="database" class="tab-pane">
										<form class="needs-validation" action="{{ route('notifications.store') }}" method="post">
											@csrf
											<div class="form-group">
												<div class="custom-control custom-radio custom-control-inline">
													<input type="radio" class="custom-control-input" id="individual2" name="user_amount" value="individual" checked>
													<label class="custom-control-label" for="individual2">Individual</label>
												</div>
												<div class="custom-control custom-radio custom-control-inline">
													<input type="radio" class="custom-control-input" id="all-user2" name="user_amount" value="all-user">
													<label class="custom-control-label" for="all-user2">All user</label>
												</div>
											</div>
											<div class="form-group">
												<label for="email2">Email:</label>
												<input type="email" name="email" value="{{ $email ?? '' }}" class="form-control" placeholder="Enter email ID" id="email2" required>
												<div class="valid-feedback">Valid.</div>
												<div class="invalid-feedback">Please fill out this field.</div>
											</div>
											<div class="form-group">
												<label for="subject2">Subject:</label>
												<input type="text" name="subject" class="form-control" placeholder="Subject of email" id="subject2" required>
												<div class="valid-feedback">Valid.</div>
												<div class="invalid-feedback">Please fill out this field.</div>
											</div>
											<!-- toolbar with suitable buttons and dialogues -->
											<div class="form-group">
												<label for="message2">Message:</label>
												<textarea name="body" class="form-control editor-tools" rows="5" id="message2" required></textarea>
												<div class="valid-feedback">Valid.</div>
												<div class="invalid-feedback">Please fill out this field.</div>
											</div>
											<button type="submit" name="database" class="btn btn-theme" value="database">Submit</button>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@section('style')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.css" rel="stylesheet">
@endsection
@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.js"></script>
    <script>
		$('.editor-tools').summernote({
			placeholder: 'Enter email body',
			tabsize: 2,
			height: 100
		});
		(function() {
			var individual = [];
			var all_user = [];
			for(let i=0; i<2; i++) {
				individual[i] = document.getElementById("individual"+(i+1));
				all_user[i] = document.getElementById("all-user"+(i+1));
				individual[i].addEventListener('change', function() {
					if( individual[i].checked ) { 
						document.getElementById("email"+(i+1)).disabled = false;
					} else {
						document.getElementById("email"+(i+1)).disabled = true;
						console.log(2);
					}
				});
				all_user[i].addEventListener('change', function() {
					if( all_user.checked ) { 
						document.getElementById("email"+(i+1)).disabled = false; 
					} else {
						document.getElementById("email"+(i+1)).disabled = true; 
					}
				});
			}
		})();
    </script>
@endsection